workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      ios_signing:
        certificates:
          - pem_cert # ou le nom de ton certificat PEM
        provisioning_profiles:
          - Smooth_last.mobileprovision
      xcode: latest
      cocoapods: default
      vars:
        XCODE_PROJECT: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.henrikanda.smoothai"
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS app
        script: flutter build ios --release --no-codesign
      - name: Build iOS app bundle
        script: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -archivePath build/Runner.xcarchive clean archive -allowProvisioningUpdates -sdk iphoneos -destination 'generic/platform=iOS'
          xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/ios -allowProvisioningUpdates
    artifacts:
      - build/ios/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_API_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: true 