workflows:
  ios-workflow:
    name: iOS Workflow (Auto Code Signing)
    max_build_duration: 60
    environment:
      xcode: latest # ou '16.0' si tu veux forcer la version
      cocoapods: default
      flutter: stable
      groups:
        - Variables # ou le nom de ton groupe de variables App Store Connect
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Install iOS dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS app (auto code signing)
        script: |
          flutter build ios --release
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
      - ios/build/archive/*.xcarchive
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_app_store: true
        submit_to_testflight: true 