workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest
      cocoapods: default
      groups:
        - ios-certificates
      vars:
        XCODE_PROJECT: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.henrikanda.smoothai"
        BUILD_CERTIFICATE_PASSWORD: "RABE2024"
        KEYCHAIN_PASSWORD: "temp"
    scripts:
      - name: Set up code signing settings
        script: |
          keychain_name="codemagic.keychain"
          keychain_password="temp"
          
          # Create keychain
          security create-keychain -p "$keychain_password" "$keychain_name"
          security list-keychains -s "$keychain_name"
          security default-keychain -s "$keychain_name"
          security unlock-keychain -p "$keychain_password" "$keychain_name"
          security set-keychain-settings -t 3600 -l ~/Library/Keychains/"$keychain_name"
          
          # Import certificates
          echo "$BUILD_CERTIFICATE_BASE64" | base64 --decode > /tmp/build_certificate.p12
          security import /tmp/build_certificate.p12 -k "$keychain_name" -P "RABE2024" -T /usr/bin/codesign || echo "Certificate import failed, trying without password"
          security import /tmp/build_certificate.p12 -k "$keychain_name" -T /usr/bin/codesign || echo "Certificate import failed completely"
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$keychain_password" "$keychain_name"
          
          # Import private key
          echo "$CERTIFICATE_PRIVATE_KEY" | base64 --decode > /tmp/certificate_private_key.p8
          security import /tmp/certificate_private_key.p8 -k "$keychain_name" -P "RABE2024" -T /usr/bin/codesign || echo "Private key import failed"
          
          # Set up provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$PROVISIONING_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/7BHY8D9X9V.com.henrikanda.smoothai.mobileprovision
          
          # List available profiles for debugging
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
          
          # List available certificates
          security find-identity -v -p codesigning
          
          # Set up App Store Connect API key
          mkdir -p ~/.appstoreconnect/private_keys
          echo "$APP_STORE_CONNECT_API_KEY_BASE64" | base64 --decode > ~/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_API_KEY_ID.p8
          chmod 600 ~/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_API_KEY_ID.p8
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
      - name: Build iOS app bundle
        script: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -archivePath build/Runner.xcarchive clean archive -allowProvisioningUpdates -sdk iphoneos -destination 'generic/platform=iOS' CODE_SIGN_IDENTITY="Apple Distribution: Henri-Vincent Kanda (7BHY8D9X9V)" PROVISIONING_PROFILE="7BHY8D9X9V.com.henrikanda.smoothai"
          xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/ios -allowProvisioningUpdates
    artifacts:
      - build/ios/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY_BASE64
        key_id: $APP_STORE_CONNECT_API_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true 