workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest
      cocoapods: default
      groups:
        - ios-certificates
      vars:
        XCODE_PROJECT: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.henrikanda.smoothai"
        BUILD_CERTIFICATE_PASSWORD: "RABE2024"
        KEYCHAIN_PASSWORD: "temp"

    scripts:
      - name: Set up code signing settings
        script: |
          keychain_name="codemagic.keychain"
          keychain_password="temp"
          
          # Create keychain
          security create-keychain -p "$keychain_password" "$keychain_name"
          security list-keychains -s "$keychain_name"
          security default-keychain -s "$keychain_name"
          security unlock-keychain -p "$keychain_password" "$keychain_name"
          security set-keychain-settings -t 3600 -l ~/Library/Keychains/"$keychain_name"
          
          # Import certificate to keychain
          echo $BUILD_CERTIFICATE_BASE64 | base64 --decode > /tmp/certificate.p12
          security import /tmp/certificate.p12 -k "$keychain_name" -P "$BUILD_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$keychain_password" "$keychain_name"
          
          # Setup provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$PROVISIONING_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision
          
          # Create private key from private key content
          if [ ! -z "$CERTIFICATE_PRIVATE_KEY" ]; then
            echo "$CERTIFICATE_PRIVATE_KEY" > /tmp/private_key.pem
            security import /tmp/private_key.pem -k "$keychain_name" -T /usr/bin/codesign
          fi
          
          # Configure App Store Connect API access
          mkdir -p ~/.appstoreconnect/private_keys
          cat > ~/.appstoreconnect/private_keys/AuthKey_4V6GWRQFC9.p8 << EOL
          -----BEGIN PRIVATE KEY-----
          MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkMgjuZYt4R2t4CwX
          PsxArZs2EBzkuWLLW67g3rZDxOugCgYIKoZIzj0DAQehRANCAATXyLEQeX6CCDmI
          0UO8xFiFbWaJWz1okKrDRGsy2VMDJLHrUaxWxJD49PVB+IyOtV5Aot5/9DBEBy0d
          eNUULbC8
          -----END PRIVATE KEY-----
          EOL
          chmod 600 ~/.appstoreconnect/private_keys/AuthKey_4V6GWRQFC9.p8
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
      - name: Build iOS app bundle
        script: |
          cd ios
          
          # Debug: List files in ios directory
          echo "Files in ios directory:"
          ls -la
          
          # Debug: List available certificates
          echo "Available certificates:"
          security find-identity -v -p codesigning || echo "No certificates found"
          
          # Debug: List provisioning profiles
          echo "Available provisioning profiles:"
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/ || echo "No profiles found"
          
          # Build directly with xcodebuild
          echo "Building with xcodebuild..."
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -archivePath build/Runner.xcarchive clean archive -allowProvisioningUpdates -sdk iphoneos -destination 'generic/platform=iOS' -allowProvisioningDeviceRegistration
          
          # Export the archive
          echo "Exporting archive..."
          xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/ios -allowProvisioningUpdates
    artifacts:
      - build/ios/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        api_key: |
          -----BEGIN PRIVATE KEY-----
          MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkMgjuZYt4R2t4CwX
          PsxArZs2EBzkuWLLW67g3rZDxOugCgYIKoZIzj0DAQehRANCAATXyLEQeX6CCDmI
          0UO8xFiFbWaJWz1okKrDRGsy2VMDJLHrUaxWxJD49PVB+IyOtV5Aot5/9DBEBy0d
          eNUULbC8
          -----END PRIVATE KEY-----
        key_identifier: "4V6GWRQFC9"
        issuer_identifier: "bbd1db28-6a57-409f-860f-cfc657430d67"
        submit_to_testflight: true 