workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
      flutter: stable
      vars:
        XCODE_PROJECT: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.henrikanda.smoothai"
        TEAM_ID: "7BHY8D9X9V"
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
        APPSTORE_CONNECT_API_KEY_ID: ${{ secrets.APPSTORE_CONNECT_API_KEY_ID }}
        APPSTORE_CONNECT_ISSUER_ID: ${{ secrets.APPSTORE_CONNECT_ISSUER_ID }}
        APPSTORE_CONNECT_API_KEY: ${{ secrets.APPSTORE_CONNECT_API_KEY }}
    scripts:
      - name: Setup iOS code signing
        script: |
          # Create certificates directory
          mkdir -p ios/certs
          
          # Remove existing keychain if it exists
          security delete-keychain login.keychain 2>/dev/null || true
          
          # Setup keychain
          security create-keychain -p "password" login.keychain
          security list-keychains -s login.keychain
          security default-keychain -s login.keychain
          security unlock-keychain -p "password" login.keychain
          security set-keychain-settings -t 3600 -l ~/Library/Keychains/login.keychain-db
          
          # Import certificates if they exist
          if [ -f "ios/certs/distribution_certificate.p12" ]; then
            security import ios/certs/distribution_certificate.p12 -k login.keychain -P "" -T /usr/bin/codesign
          fi
          
          # Setup API key for App Store Connect
          mkdir -p ~/.appstoreconnect/private_keys
          
          # Use the API key ID directly (4V6GWRQFC9)
          API_KEY_ID="4V6GWRQFC9"
          echo "$APPSTORE_CONNECT_API_KEY" > ~/.appstoreconnect/private_keys/AuthKey_${API_KEY_ID}.p8
          chmod 600 ~/.appstoreconnect/private_keys/AuthKey_${API_KEY_ID}.p8
          
          echo "API key setup completed for key ID: ${API_KEY_ID}"
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Install iOS dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
      - name: Build and archive iOS app
        script: |
          cd ios
          fastlane build
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        api_key: $APPSTORE_CONNECT_API_KEY
        key_id: $APPSTORE_CONNECT_API_KEY_ID
        issuer_id: $APPSTORE_CONNECT_ISSUER_ID
        submit_to_app_store: true
        submit_to_testflight: true 