workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
      flutter: stable
      vars:
        XCODE_PROJECT: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.henrikanda.smoothai"
        TEAM_ID: "7BHY8D9X9V"
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
        APPSTORE_CONNECT_API_KEY_ID: ${{ secrets.APPSTORE_CONNECT_API_KEY_ID }}
        APPSTORE_CONNECT_ISSUER_ID: ${{ secrets.APPSTORE_CONNECT_ISSUER_ID }}
        APPSTORE_CONNECT_API_KEY: ${{ secrets.APPSTORE_CONNECT_API_KEY }}
    scripts:
      - name: Setup iOS code signing
        script: |
          # Create certificates directory
          mkdir -p ios/certs
          
          # Remove existing keychain if it exists
          security delete-keychain login.keychain 2>/dev/null || true
          
          # Setup keychain
          security create-keychain -p "password" login.keychain
          security list-keychains -s login.keychain
          security default-keychain -s login.keychain
          security unlock-keychain -p "password" login.keychain
          security set-keychain-settings -t 3600 -l ~/Library/Keychains/login.keychain-db
          
          # Import certificates if they exist
          if [ -f "ios/certs/distribution_certificate.p12" ]; then
            security import ios/certs/distribution_certificate.p12 -k login.keychain -P "" -T /usr/bin/codesign
          fi
          
          # Copy the .p8 file to the current directory for Fastlane
          cp ios/AuthKey_4V6GWRQFC9.p8 ./AuthKey_4V6GWRQFC9.p8
          chmod 600 ./AuthKey_4V6GWRQFC9.p8
          
          echo "API key file copied for Fastlane"
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Install iOS dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS app without code signing
        script: |
          flutter build ios --release --no-codesign
      - name: Create archive without code signing
        script: |
          cd ios
          mkdir -p build/archive
          
          # Archive the app without code signing
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -archivePath build/archive/Runner.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          
          echo "Archive created successfully"
          ls -la build/archive/
      - name: Create unsigned IPA
        script: |
          cd ios
          mkdir -p build/ios/ipa
          
          # Export to IPA without code signing
          xcodebuild -exportArchive -archivePath build/archive/Runner.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/ios/ipa CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          
          echo "Unsigned IPA created successfully"
          ls -la build/ios/ipa/
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
      - ios/build/archive/*.xcarchive
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        api_key: $APPSTORE_CONNECT_API_KEY
        key_id: $APPSTORE_CONNECT_API_KEY_ID
        issuer_id: $APPSTORE_CONNECT_ISSUER_ID
        submit_to_app_store: true
        submit_to_testflight: true 