name: smooth_ai_dating_assistant
description: Smooth AI - Votre Assistant de Rencontres Ultime

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Backend et authentification
  supabase_flutter: ^2.5.0
  
  # Stockage local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Notifications
  flutter_local_notifications: ^19.3.0
  
  # Réseau et connectivité
  http: ^1.2.1
  connectivity_plus: ^6.1.4
  
  # Interface utilisateur
  lottie: ^3.2.0
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  
  # Médias et fichiers
  file_picker: ^10.2.0
  image_picker: ^1.1.1
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.2
  
  # Audio
  
  # ML et IA
  # google_ml_kit: ^0.20.0  # Pas nécessaire - on utilise Vision API cloud
  # flutter_tesseract_ocr: ^0.4.28
  
  # Achats in-app
  in_app_purchase: ^3.1.13
  in_app_purchase_android: ^0.3.6+13
  in_app_purchase_storekit: ^0.3.20
  
  # Utilitaires
  cupertino_icons: ^1.0.8
  uuid: ^4.2.2
  intl: ^0.19.0
  collection: ^1.18.0
  logging: ^1.2.0
  html: ^0.15.6
  syncfusion_flutter_pdf: ^28.1.44
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  permission_handler: ^11.3.1
#  image_cropper: ^7.0.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  dio: ^5.4.1
  json_annotation: ^4.9.0

  infinite_carousel: ^1.1.1
  app_links: ^3.4.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  mocktail: ^1.0.4
  test: ^1.25.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  
  # Assets configuration
  assets:
    - assets/images/
    - assets/sounds/
    - assets/animations/
    - assets/images/leSmenu.png
    - assets/images/instagram.png
    - assets/images/tiktok.png
    - assets/images/facebook.png
    - assets/images/snapchat.png
    - assets/images/logo.png
    - assets/images/capturemilieurscreen1.png
    - assets/images/capturemilieurscreen2.png
    - assets/sounds/error.mp3
    - assets/sounds/success.mp3
    - assets/sounds/notification.mp3
    - assets/sounds/message.mp3
    - assets/fonts/SFProDisplay-Regular.ttf
    - assets/fonts/SFProDisplay-Bold.ttf
    - assets/fonts/SFProDisplay-Black.ttf


# === AJOUT POUR LES SONS MANQUANTS ===
# Placez les fichiers suivants dans assets/sounds/ :
#   - success.mp3
#   - error.mp3
#   - notification.mp3
#   - message.mp3
# Vous pouvez utiliser des sons libres de droits ou des sons de test.
# Sans ces fichiers, l'application affichera des erreurs d'assets manquants.
# ================================

dependency_overrides:
  in_app_purchase_storekit: 0.3.19  # Version stable exacte
  in_app_purchase_android: 0.3.6+13
