import '../models/pickup_line.dart';
import 'dart:math';

/// Service minimaliste pour générer une phrase d'accroche aléatoire
class PickupLinesService {
  static final List<PickupLine> _pickupLinesDatabase = [
    PickupLine(id: 'c1', text: 'Excuse-moi, tu n\'aurais pas un plan ? Parce que je me perds dans tes yeux.', category: 'classiques', context: 'general', intensity: 1),
    PickupLine(id: 'c2', text: 'Est-ce que tu crois au coup de foudre, ou est-ce que je dois repasser ?', category: 'classiques', context: 'general', intensity: 1),
    PickupLine(id: 'c3', text: 'Si j\'étais un chat, je passerais mes 9 vies avec toi.', category: 'classiques', context: 'general', intensity: 1),
    PickupLine(id: 'c4', text: 'Tu dois être fatiguée, ça fait toute la nuit que tu cours dans mes pensées.', category: 'classiques', context: 'general', intensity: 2),
    PickupLine(id: 'c5', text: 'Est-ce que ton père était un voleur ? Parce qu\'il a volé les étoiles pour les mettre dans tes yeux.', category: 'classiques', context: 'general', intensity: 1),
    PickupLine(id: 'd1', text: 'Est-ce que tu es un magicien ? Parce que chaque fois que je te regarde, tout le monde disparaît.', category: 'drole', context: 'general', intensity: 1),
    PickupLine(id: 'd2', text: 'Je ne suis pas ivre, mais tu me donnes le tournis.', category: 'drole', context: 'bar', intensity: 2),
    PickupLine(id: 'd3', text: 'Est-ce que tu es un castor ? Parce que tu es dam fine !', category: 'drole', context: 'general', intensity: 2),
    PickupLine(id: 'd4', text: 'Si tu étais un légume, tu serais un chou... un chou mignon !', category: 'drole', context: 'general', intensity: 1),
    PickupLine(id: 'd5', text: 'Est-ce que tu es WiFi ? Parce que je sens une connexion.', category: 'drole', context: 'general', intensity: 2),
    PickupLine(id: 'i1', text: 'Si tu étais une équation mathématique, tu serais l\'infini, car tu n\'as pas de limite.', category: 'intellectuel', context: 'general', intensity: 2),
    PickupLine(id: 'i2', text: 'Tu dois être la racine carrée de -1, parce que tu es imaginairement parfaite.', category: 'intellectuel', context: 'general', intensity: 2),
    PickupLine(id: 'i3', text: 'Si j\'étais Sartre, je dirais que tu es mon être-pour-autrui.', category: 'intellectuel', context: 'general', intensity: 3),
    PickupLine(id: 'i4', text: 'Tu es comme la constante de Planck : fondamentale à mon univers.', category: 'intellectuel', context: 'general', intensity: 2),
    PickupLine(id: 'i5', text: 'Si l\'amour était une science, tu serais ma théorie unifiée.', category: 'intellectuel', context: 'general', intensity: 2),
    PickupLine(id: 'dir1', text: 'Je trouve que tu es vraiment attirante. Ça te dirait qu\'on apprenne à se connaître ?', category: 'directe', context: 'general', intensity: 3),
    PickupLine(id: 'dir2', text: 'Je ne vais pas tourner autour du pot : tu me plais beaucoup.', category: 'directe', context: 'general', intensity: 4),
    PickupLine(id: 'dir3', text: 'Excuse-moi, mais je ne pouvais pas partir sans te dire que tu es magnifique.', category: 'directe', context: 'general', intensity: 3),
    PickupLine(id: 'dir4', text: 'Je sais que c\'est direct, mais j\'aimerais t\'inviter à boire un verre.', category: 'directe', context: 'bar', intensity: 4),
    PickupLine(id: 'dir5', text: 'Tu m\'attires vraiment. Peut-on discuter ?', category: 'directe', context: 'general', intensity: 3),
    // --- Ajout de 200 nouvelles pickup lines osées/sexy/chandes ---
    PickupLine(id: 'x1', text: 'Si tu étais une appli, je te mettrais en plein écran toute la nuit.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x2', text: 'J’espère que tu es une électricienne, parce que tu fais grimper ma tension.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x3', text: 'Je ne suis pas photographe, mais je peux nous imaginer ensemble… sans vêtements.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x4', text: 'Si tu étais un rêve, je ne voudrais jamais me réveiller… surtout si tu es dans mon lit.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x5', text: 'Tu dois être une alarme incendie, parce que tu fais monter la température.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x6', text: 'Je ne suis pas astrologue, mais je vois une nuit torride dans notre avenir.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x7', text: 'Si tu étais un dessert, tu serais 100% aphrodisiaque.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x8', text: 'J’espère que tu aimes les surprises… surtout sous les draps.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x9', text: 'Je ne suis pas un voleur, mais j’aimerais bien te dérober toute la nuit.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x10', text: 'Si tu étais un cocktail, tu serais explosif… et j’ai très soif.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x11', text: 'Tu dois être un volcan, parce que tu fais fondre tous mes vêtements.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x12', text: 'Je ne suis pas magicien, mais je peux faire disparaître tes habits.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x13', text: 'Si tu étais une chanson, je te passerais en boucle toute la nuit.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x14', text: 'J’espère que tu es prête à transpirer, parce que je ne compte pas dormir.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x15', text: 'Tu dois être un secret bien gardé, parce que j’ai envie de te découvrir.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x16', text: 'Si tu étais un lit, je ne te quitterais jamais.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x17', text: 'Je ne suis pas marathonien, mais je peux tenir toute la nuit.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x18', text: 'Tu dois être une étoile filante, parce que j’ai envie de faire un vœu très coquin.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x19', text: 'Si tu étais un jeu vidéo, je passerais tous mes niveaux avec toi… sans sauvegarde.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x20', text: 'J’espère que tu aimes les défis, parce que je suis prêt à te faire rougir.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x21', text: 'Si tu étais une page web, je te mettrais dans mes favoris pour la nuit.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x22', text: 'J’ai envie de t’écrire un roman… mais on va commencer par un chapitre sous la couette.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x23', text: 'Si tu étais une énigme, je passerais la nuit à te résoudre.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x24', text: 'Je ne suis pas DJ, mais je peux te faire vibrer toute la nuit.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x25', text: 'Si tu étais une chanson, je voudrais te remixer en version très sensuelle.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x26', text: 'J’espère que tu aimes les jeux de rôle… parce que j’ai plein d’idées.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x27', text: 'Si tu étais une étoile, je passerais la nuit à te contempler… et à te toucher.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x28', text: 'Je ne suis pas chef, mais j’ai envie de goûter à tous tes plats… et à toi.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x29', text: 'Si tu étais un secret, je voudrais te murmurer toute la nuit.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x30', text: 'J’espère que tu es prête à perdre le contrôle… parce que je ne vais pas freiner.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x31', text: 'Si tu étais un film, je voudrais voir la version non-censurée.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x32', text: 'Je ne suis pas masseur, mais je peux te détendre comme personne.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x33', text: 'Si tu étais une tempête, je voudrais me faire emporter toute la nuit.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x34', text: 'J’espère que tu aimes les nuits blanches… parce que je ne compte pas dormir.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x35', text: 'Si tu étais un parfum, je voudrais t’avoir sur ma peau jusqu’au matin.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x36', text: 'Je ne suis pas poète, mais j’ai envie d’écrire sur ton corps.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x37', text: 'Si tu étais une vague, je voudrais me laisser submerger.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x38', text: 'J’espère que tu aimes les surprises… surtout quand la lumière s’éteint.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x39', text: 'Si tu étais un feu, je voudrais brûler avec toi.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x40', text: 'Je ne suis pas somnambule, mais j’ai envie de marcher sur ton corps toute la nuit.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x41', text: 'Si tu étais un livre, je te lirais encore et encore... surtout les chapitres coquins.', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x42', text: 'Je ne suis pas un oreiller, mais tu peux me mordre si tu veux...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x43', text: 'Ton corps est ma nouvelle religion, et je suis là pour prier toute la nuit...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x44', text: 'Je ne suis pas un cordonnier, mais je peux certainement te faire jouir...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x45', text: 'Si le plaisir était une piscine, je te ferais faire des longueurs...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x46', text: 'Tes courbes sont comme des routes sinueuses, et j\'ai envie de toutes les explorer...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x47', text: 'Je ne suis pas un livre, mais tu peux me lire toute la nuit...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x48', text: 'Si je te dis que je suis accro à toi, tu seras ma drogue ?', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x49', text: 'Ton sourire me donne des idées très peu catholiques...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x50', text: 'Je ne suis pas un vampire, mais je pourrais bien te sucer le cou...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x51', text: 'Si le baiser était une langue, je serais bilingue...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x52', text: 'Ton corps est une invitation que j\'ai très envie d\'accepter...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x53', text: 'Je ne suis pas un bon danseur, mais je sais très bien bouger au lit...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x54', text: 'Si tu étais un fruit, tu serais une pêche... et j\'ai très envie de te croquer...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x55', text: 'Ton regard me fait fondre comme du chocolat chaud... et j\'ai envie de te lécher partout...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x56', text: 'Je ne suis pas un chef étoilé, mais je peux te faire cuisiner toute la nuit...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x57', text: 'Si tu étais une boisson, je te boirais à petites gorgées... très lentement...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x58', text: 'Ton parfum est mon aphrodisiaque préféré...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x59', text: 'Je ne suis pas un oreiller, mais tu peux crier dedans...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x60', text: 'Si tu étais un dessert, je te dégusterais avec délectation...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x61', text: 'Tes lèvres ont l\'air douces... j\'aimerais savoir si c\'est le cas partout...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x62', text: 'Je ne suis pas un photographe, mais j\'aimerais bien prendre quelques clichés... en privé...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x63', text: 'Si tu étais une musique, tu serais ma chanson préférée... celle que j\'écoute en boucle...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x64', text: 'Ton rire est ma mélodie préférée... surtout quand je le fais naître...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x65', text: 'Je ne suis pas un jardinier, mais je sais comment faire pousser ton plaisir...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x66', text: 'Si tu étais une étoile, je passerais ma vie à te contempler... toute nue...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x67', text: 'Tes mains sur mon corps seraient le début d\'une belle aventure...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x68', text: 'Je ne suis pas un magicien, mais je peux faire disparaître tes vêtements...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x69', text: 'Si tu étais un jeu, je jouerais avec toi toute la nuit...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x70', text: 'Ton corps est une carte au trésor, et je suis prêt à explorer chaque recoin...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x71', text: 'Je ne suis pas un électricien, mais je peux te faire prendre du courant...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x72', text: 'Si tu étais un dessert, je te dégusterais avec les doigts...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x73', text: 'Ton regard est plus enivrant que le meilleur des vins...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x74', text: 'Je ne suis pas un artiste, mais je peux faire de ton corps une œuvre d\'art...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x75', text: 'Si tu étais une gourmandise, je te mangerais toute la nuit...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x76', text: 'Tes lèvres sont comme du vin... plus je les goûte, plus j\'en veux...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x77', text: 'Je ne suis pas un sportif, mais je peux te faire courir de plaisir...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x78', text: 'Si tu étais une note de musique, tu serais ma préférée... celle qui me fait vibrer...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x79', text: 'Ton corps est une invitation que je ne peux pas refuser...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x80', text: 'Je ne suis pas un chef, mais je peux te faire mijoter de plaisir...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x81', text: 'Si tu étais un voyage, je ne voudrais jamais en revenir...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x82', text: 'Je ne suis pas un oreiller, mais tu peux t\'agripper à moi...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x83', text: 'Ton corps est ma drogue... et j\'ai besoin de ma dose...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x84', text: 'Si tu étais un crime, je serais ton complice...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x85', text: 'Je ne suis pas un boulanger, mais je peux te faire lever...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x86', text: 'Tes lèvres sont comme du miel... et j\'ai une petite faim...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x87', text: 'Si tu étais un rêve, je ne voudrais jamais me réveiller...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x88', text: 'Je ne suis pas un magicien, mais je peux te faire disparaître sous les draps...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x89', text: 'Ton corps est une œuvre d\'art... et je veux l\'admirer sous tous les angles...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x90', text: 'Si tu étais une gourmandise, je te dévorerais...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x91', text: 'Je ne suis pas un sportif, mais je peux te faire courir de plaisir...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x92', text: 'Tes courbes sont comme une route de montagne... et j\'ai envie de les explorer...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x93', text: 'Si tu étais une boisson, je te boirais à petites gorgées...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x94', text: 'Je ne suis pas un photographe, mais j\'aimerais capturer chaque parcelle de ton corps...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x95', text: 'Ton rire est ma mélodie préférée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x96', text: 'Si tu étais un jeu, je jouerais avec toi toute la nuit...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x97', text: 'Je ne suis pas un jardinier, mais je peux arroser tes fleurs...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x98', text: 'Ton regard est plus enivrant que le meilleur des vins...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x99', text: 'Si tu étais une étoile, je passerais ma vie à te contempler...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x100', text: 'Je ne suis pas un électricien, mais je peux te faire prendre du courant...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x101', text: 'Tes lèvres sont comme du vin... plus je les goûte, plus j\'en veux...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x102', text: 'Si tu étais un dessert, je te dégusterais avec les doigts...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x103', text: 'Je ne suis pas un artiste, mais je peux faire de ton corps une œuvre d\'art...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x104', text: 'Ton corps est une invitation que je ne peux pas refuser...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x105', text: 'Si tu étais une gourmandise, je te mangerais toute la nuit...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x106', text: 'Je ne suis pas un chef, mais je peux te faire mijoter de plaisir...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x107', text: 'Tes mains sur mon corps seraient le début d\'une belle aventure...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x108', text: 'Si tu étais une note de musique, tu serais ma préférée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x109', text: 'Je ne suis pas un magicien, mais je peux faire disparaître tes vêtements...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x110', text: 'Ton corps est une carte au trésor, et je suis prêt à explorer chaque recoin...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x111', text: 'Si tu étais un fruit, tu serais une pêche... et j\'ai très envie de te croquer...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x112', text: 'Je ne suis pas un cordonnier, mais je peux certainement te faire jouir...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x113', text: 'Ton regard me fait fondre comme du chocolat chaud...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x114', text: 'Si tu étais une boisson, je te boirais à petites gorgées... très lentement...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x115', text: 'Je ne suis pas un chef étoilé, mais je peux te faire cuisiner toute la nuit...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x116', text: 'Tes courbes sont comme des routes sinueuses, et j\'ai envie de toutes les explorer...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x117', text: 'Si tu étais un livre, je te lirais encore et encore...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x118', text: 'Je ne suis pas un oreiller, mais tu peux me mordre si tu veux...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x119', text: 'Ton corps est ma nouvelle religion, et je suis là pour prier toute la nuit...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x120', text: 'Si le plaisir était une piscine, je te ferais faire des longueurs...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x121', text: 'Ton corps est ma drogue... et j\'ai besoin de ma dose quotidienne...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x122', text: 'Si tu étais un dessert, je te dégusterais à la petite cuillère...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x123', text: 'Tes lèvres sont comme du miel... j\'ai envie d\'y goûter encore et encore...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x124', text: 'Je ne suis pas un photographe, mais j\'aimerais capturer chaque parcelle de ton corps...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x125', text: 'Si tu étais une étoile, je passerais ma vie à te contempler...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x126', text: 'Ton regard est plus enivrant que le meilleur des vins...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x127', text: 'Je ne suis pas un jardinier, mais je peux m\'occuper de ta petite fleur...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x128', text: 'Si tu étais un jeu, je jouerais avec toi toute la nuit...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x129', text: 'Tes courbes sont comme une route de montagne... j\'ai envie de les explorer...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x130', text: 'Je ne suis pas un sportif, mais je peux te faire courir de plaisir...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x131', text: 'Si tu étais une gourmandise, je te mangerais toute la nuit...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x132', text: 'Ton corps est une invitation que je ne peux pas refuser...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x133', text: 'Je ne suis pas un artiste, mais je peux faire de ton corps une œuvre d\'art...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x134', text: 'Si tu étais un dessert, je te dégusterais avec les doigts...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x135', text: 'Tes lèvres sont comme du vin... plus je les goûte, plus j\'en veux...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x136', text: 'Je ne suis pas un électricien, mais je peux te faire prendre du courant...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x137', text: 'Ton corps est une carte au trésor, et je suis prêt à explorer chaque recoin...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x138', text: 'Je ne suis pas un magicien, mais je peux faire disparaître tes vêtements...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x139', text: 'Si tu étais une note de musique, tu serais ma préférée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x140', text: 'Tes mains sur mon corps seraient le début d\'une belle aventure...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x141', text: 'Je ne suis pas un chef, mais je peux te faire mijoter de plaisir...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x142', text: 'Si tu étais une gourmandise, je te mangerais toute la nuit...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x143', text: 'Ton corps est une invitation que je ne peux pas refuser...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x144', text: 'Je ne suis pas un artiste, mais je peux faire de ton corps une œuvre d\'art...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x145', text: 'Si tu étais un dessert, je te dégusterais avec les doigts...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x146', text: 'Tes lèvres sont comme du vin... plus je les goûte, plus j\'en veux...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x147', text: 'Je ne suis pas un électricien, mais je peux te faire prendre du courant...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x148', text: 'Ton corps est une carte au trésor, et je suis prêt à explorer chaque recoin...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x149', text: 'Je ne suis pas un magicien, mais je peux faire disparaître tes vêtements...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x150', text: 'Si tu étais une note de musique, tu serais ma préférée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x151', text: 'Tes mains sur mon corps seraient le début d\'une belle aventure...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x152', text: 'Je ne suis pas un chef, mais je peux te faire mijoter de plaisir...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x153', text: 'Si tu étais une gourmandise, je te mangerais toute la nuit...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x154', text: 'Ton corps est une invitation que je ne peux pas refuser...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x155', text: 'Je ne suis pas un artiste, mais je peux faire de ton corps une œuvre d\'art...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x156', text: 'Si tu étais un dessert, je te dégusterais avec les doigts...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x157', text: 'Tes lèvres sont comme du vin... plus je les goûte, plus j\'en veux...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x158', text: 'Je ne suis pas un électricien, mais je peux te faire prendre du courant...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x159', text: 'Ton corps est une carte au trésor, et je suis prêt à explorer chaque recoin...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x160', text: 'Je ne suis pas un magicien, mais je peux faire disparaître tes vêtements...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x161', text: 'Ton corps est ma drogue... et j\'ai besoin de ma dose quotidienne...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x162', text: 'Si tu étais un dessert, je te dégusterais à la petite cuillère...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x163', text: 'Tes lèvres sont comme du miel... j\'ai envie d\'y goûter encore et encore...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x164', text: 'Je ne suis pas un photographe, mais j\'aimerais capturer chaque parcelle de ton corps...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x165', text: 'Si tu étais une étoile, je passerais ma vie à te contempler...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x166', text: 'Ton regard est plus enivrant que le meilleur des vins...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x167', text: 'Je ne suis pas un jardinier, mais je peux m\'occuper de ta petite fleur...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x168', text: 'Si tu étais un jeu, je jouerais avec toi toute la nuit...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x169', text: 'Tes courbes sont comme une route de montagne... j\'ai envie de les explorer...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x170', text: 'Je ne suis pas un sportif, mais je peux te faire courir de plaisir...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x171', text: 'Si tu étais une gourmandise, je te mangerais toute la nuit...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x172', text: 'Ton corps est une invitation que je ne peux pas refuser...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x173', text: 'Je ne suis pas un artiste, mais je peux faire de ton corps une œuvre d\'art...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x174', text: 'Si tu étais un dessert, je te dégusterais avec les doigts...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x175', text: 'Tes lèvres sont comme du vin... plus je les goûte, plus j\'en veux...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x176', text: 'Je ne suis pas un électricien, mais je peux te faire prendre du courant...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x177', text: 'Ton corps est une carte au trésor, et je suis prêt à explorer chaque recoin...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x178', text: 'Je ne suis pas un magicien, mais je peux faire disparaître tes vêtements...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x179', text: 'Si tu étais une note de musique, tu serais ma préférée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x180', text: 'Tes mains sur mon corps seraient le début d\'une belle aventure...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x181', text: 'Je ne suis pas un chef, mais je peux te faire mijoter de plaisir...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x182', text: 'Si tu étais une gourmandise, je te mangerais toute la nuit...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x183', text: 'Ton corps est une invitation que je ne peux pas refuser...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x184', text: 'Je ne suis pas un artiste, mais je peux faire de ton corps une œuvre d\'art...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x185', text: 'Si tu étais un dessert, je te dégusterais avec les doigts...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x186', text: 'Tes lèvres sont comme du vin... plus je les goûte, plus j\'en veux...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x187', text: 'Je ne suis pas un électricien, mais je peux te faire prendre du courant...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x188', text: 'Ton corps est une carte au trésor, et je suis prêt à explorer chaque recoin...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x189', text: 'Je ne suis pas un magicien, mais je peux faire disparaître tes vêtements...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x190', text: 'Si tu étais une note de musique, tu serais ma préférée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x191', text: 'Tes mains sur mon corps seraient le début d\'une belle aventure...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x192', text: 'Je ne suis pas un chef, mais je peux te faire mijoter de plaisir...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x193', text: 'Si tu étais une gourmandise, je te mangerais toute la nuit...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x194', text: 'Ton corps est une invitation que je ne peux pas refuser...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x195', text: 'Je ne suis pas un artiste, mais je peux faire de ton corps une œuvre d\'art...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x196', text: 'Si tu étais un dessert, je te dégusterais avec les doigts...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x197', text: 'Tes lèvres sont comme du vin... plus je les goûte, plus j\'en veux...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x198', text: 'Je ne suis pas un électricien, mais je peux te faire prendre du courant...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x199', text: 'Ton corps est une carte au trésor, et je suis prêt à explorer chaque recoin...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x200', text: 'Je ne suis pas un magicien, mais je peux faire disparaître tes vêtements...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'x201', text: 'Si tu étais une note de musique, tu serais ma préférée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't1', text: 'Ton sourire est comme le soleil, il réchauffe mon cœur à chaque fois que je le vois...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't2', text: 'Si le bonheur avait une odeur, ça sentirait tes cheveux au petit matin...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't3', text: 'Je ne suis pas un photographe, mais je peux certainement te mettre en valeur...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't4', text: 'Tes yeux sont comme des étoiles, ils brillent chaque fois que tu me regardes...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't5', text: 'Si tu étais un fruit, tu serais une pêche... douce et juteuse...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't6', text: 'Je ne suis pas un oreiller, mais tu peux t\'allonger sur moi...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't7', text: 'Ton rire est ma mélodie préférée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't8', text: 'Si tu étais un livre, je te lirais encore et encore...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't9', text: 'Je ne suis pas un chocolat, mais je fonds quand tu me touches...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't10', text: 'Tes lèvres sont comme du miel, j\'ai envie d\'y goûter...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't11', text: 'Si tu étais une étoile, tu serais la plus brillante...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't12', text: 'Je ne suis pas un oreiller, mais tu peux me serrer fort...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't13', text: 'Ton sourire est comme un rayon de soleil dans ma journée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't14', text: 'Si tu étais une fleur, tu serais une rose... belle et délicate...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't15', text: 'Je ne suis pas un photographe, mais je peux certainement te mettre en valeur...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't16', text: 'Tes yeux sont comme des étoiles, ils brillent chaque fois que tu me regardes...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't17', text: 'Si tu étais un fruit, tu serais une pêche... douce et juteuse...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't18', text: 'Je ne suis pas un oreiller, mais tu peux t\'allonger sur moi...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't19', text: 'Ton rire est ma mélodie préférée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't20', text: 'Si tu étais un livre, je te lirais encore et encore...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't21', text: 'Je ne suis pas un chocolat, mais je fonds quand tu me touches...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't22', text: 'Tes lèvres sont comme du miel, j\'ai envie d\'y goûter...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't23', text: 'Si tu étais une étoile, tu serais la plus brillante...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't24', text: 'Je ne suis pas un oreiller, mais tu peux me serrer fort...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't25', text: 'Ton sourire est comme un rayon de soleil dans ma journée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't26', text: 'Si tu étais une fleur, tu serais une rose... belle et délicate...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't27', text: 'Je ne suis pas un photographe, mais je peux certainement te mettre en valeur...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't28', text: 'Tes yeux sont comme des étoiles, ils brillent chaque fois que tu me regardes...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't29', text: 'Si tu étais un fruit, tu serais une pêche... douce et juteuse...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't30', text: 'Je ne suis pas un oreiller, mais tu peux t\'allonger sur moi...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't31', text: 'Ton rire est ma mélodie préférée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't32', text: 'Si tu étais un livre, je te lirais encore et encore...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't33', text: 'Je ne suis pas un chocolat, mais je fonds quand tu me touches...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't34', text: 'Tes lèvres sont comme du miel, j\'ai envie d\'y goûter...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't35', text: 'Si tu étais une étoile, tu serais la plus brillante...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't36', text: 'Je ne suis pas un oreiller, mais tu peux me serrer fort...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't37', text: 'Ton sourire est comme un rayon de soleil dans ma journée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't38', text: 'Si tu étais une fleur, tu serais une rose... belle et délicate...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't39', text: 'Je ne suis pas un photographe, mais je peux certainement te mettre en valeur...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't40', text: 'Tes yeux sont comme des étoiles, ils brillent chaque fois que tu me regardes...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't41', text: 'Si tu étais un fruit, tu serais une pêche... douce et juteuse...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't42', text: 'Je ne suis pas un oreiller, mais tu peux t\'allonger sur moi...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't43', text: 'Ton rire est ma mélodie préférée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't44', text: 'Si tu étais un livre, je te lirais encore et encore...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't45', text: 'Je ne suis pas un chocolat, mais je fonds quand tu me touches...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't46', text: 'Tes lèvres sont comme du miel, j\'ai envie d\'y goûter...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't47', text: 'Si tu étais une étoile, tu serais la plus brillante...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't48', text: 'Je ne suis pas un oreiller, mais tu peux me serrer fort...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't49', text: 'Ton sourire est comme un rayon de soleil dans ma journée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't50', text: 'Si tu étais une fleur, tu serais une rose... belle et délicate...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't51', text: 'Ton regard est comme une drogue, une seule fois ne me suffit pas...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't52', text: 'Si tu étais un dessert, je te mangerais à la petite cuillère...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't53', text: 'Je ne suis pas un photographe, mais je peux te mettre en valeur...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't54', text: 'Tes lèvres sont comme du miel, j\'ai envie d\'y goûter...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't55', text: 'Si tu étais une étoile, tu serais la plus brillante...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't56', text: 'Je ne suis pas un oreiller, mais tu peux t\'allonger sur moi...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't57', text: 'Ton rire est ma mélodie préférée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't58', text: 'Si tu étais un livre, je te lirais encore et encore...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't59', text: 'Je ne suis pas un chocolat, mais je fonds quand tu me touches...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't60', text: 'Tes lèvres sont comme du miel, j\'ai envie d\'y goûter...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't61', text: 'Si tu étais une étoile, tu serais la plus brillante...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't62', text: 'Je ne suis pas un oreiller, mais tu peux me serrer fort...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't63', text: 'Ton sourire est comme un rayon de soleil dans ma journée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't64', text: 'Si tu étais une fleur, tu serais une rose... belle et délicate...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't65', text: 'Je ne suis pas un photographe, mais je peux certainement te mettre en valeur...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't66', text: 'Tes yeux sont comme des étoiles, ils brillent chaque fois que tu me regardes...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't67', text: 'Si tu étais un fruit, tu serais une pêche... douce et juteuse...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't68', text: 'Je ne suis pas un oreiller, mais tu peux t\'allonger sur moi...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't69', text: 'Ton rire est ma mélodie préférée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't70', text: 'Si tu étais un livre, je te lirais encore et encore...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't71', text: 'Je ne suis pas un chocolat, mais je fonds quand tu me touches...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't72', text: 'Tes lèvres sont comme du miel, j\'ai envie d\'y goûter...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't73', text: 'Si tu étais une étoile, tu serais la plus brillante...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't74', text: 'Je ne suis pas un oreiller, mais tu peux me serrer fort...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't75', text: 'Ton sourire est comme un rayon de soleil dans ma journée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't76', text: 'Si tu étais une fleur, tu serais une rose... belle et délicate...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't77', text: 'Je ne suis pas un photographe, mais je peux certainement te mettre en valeur...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't78', text: 'Tes yeux sont comme des étoiles, ils brillent chaque fois que tu me regardes...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't79', text: 'Si tu étais un fruit, tu serais une pêche... douce et juteuse...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't80', text: 'Je ne suis pas un oreiller, mais tu peux t\'allonger sur moi...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't81', text: 'Ton rire est ma mélodie préférée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't82', text: 'Si tu étais un livre, je te lirais encore et encore...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't83', text: 'Je ne suis pas un chocolat, mais je fonds quand tu me touches...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't84', text: 'Tes lèvres sont comme du miel, j\'ai envie d\'y goûter...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't85', text: 'Si tu étais une étoile, tu serais la plus brillante...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't86', text: 'Je ne suis pas un oreiller, mais tu peux me serrer fort...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't87', text: 'Ton sourire est comme un rayon de soleil dans ma journée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't88', text: 'Si tu étais une fleur, tu serais une rose... belle et délicate...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't89', text: 'Je ne suis pas un photographe, mais je peux certainement te mettre en valeur...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't90', text: 'Tes yeux sont comme des étoiles, ils brillent chaque fois que tu me regardes...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't91', text: 'Si tu étais un fruit, tu serais une pêche... douce et juteuse...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't92', text: 'Je ne suis pas un oreiller, mais tu peux t\'allonger sur moi...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't93', text: 'Ton rire est ma mélodie préférée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't94', text: 'Si tu étais un livre, je te lirais encore et encore...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't95', text: 'Je ne suis pas un chocolat, mais je fonds quand tu me touches...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't96', text: 'Tes lèvres sont comme du miel, j\'ai envie d\'y goûter...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't97', text: 'Si tu étais une étoile, tu serais la plus brillante...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't98', text: 'Je ne suis pas un oreiller, mais tu peux me serrer fort...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't99', text: 'Ton sourire est comme un rayon de soleil dans ma journée...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 't100', text: 'Si tu étais une fleur, tu serais une rose... belle et délicate...', category: 'ultra', context: 'hot', intensity: 5),
    PickupLine(id: 'a1', text: 'Ton sourire illumine ma journée comme un rayon de soleil.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a2', text: 'Tu es la personne la plus éblouissante que j\'ai jamais rencontrée.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a3', text: 'Ton rire est la plus belle des mélodies à mes oreilles.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a4', text: 'Ta beauté me coupe le souffle à chaque fois que je te vois.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a5', text: 'Ton intelligence est aussi attirante que ton sourire.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a6', text: 'Tu es la définition même de la grâce et de l\'élégance.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a7', text: 'Ton regard est comme une étoile qui guide mes pensées vers toi.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a8', text: 'Ta présence rend chaque instant magique.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a9', text: 'Tu es la personne la plus fascinante que je connaisse.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a10', text: 'Ton sourire est mon plus beau cadeau.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a11', text: 'Ta beauté intérieure brille encore plus que ta beauté extérieure.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a12', text: 'Ton esprit est aussi attirant que ton apparence.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a13', text: 'Tu es la personne la plus charmante que j\'ai jamais rencontrée.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a14', text: 'Ton sourire est mon rayon de soleil quotidien.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a15', text: 'Ta présence rend chaque journée spéciale.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a16', text: 'Tu es la personne la plus étonnante que je connaisse.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a17', text: 'Ton rire est la plus belle des musiques à mes oreilles.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a18', text: 'Ta beauté me laisse sans voix.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a19', text: 'Ton intelligence est aussi impressionnante que ta beauté.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a20', text: 'Tu es la définition même de la perfection.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a21', text: 'Ton regard est comme une étoile qui guide mes pensées vers toi.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a22', text: 'Ta présence rend chaque instant magique.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a23', text: 'Tu es la personne la plus fascinante que je connaisse.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a24', text: 'Ton sourire est mon plus beau cadeau.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a25', text: 'Ta beauté intérieure brille encore plus que ta beauté extérieure.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a26', text: 'Ton esprit est aussi attirant que ton apparence.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a27', text: 'Tu es la personne la plus charmante que j\'ai jamais rencontrée.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a28', text: 'Ton sourire est mon rayon de soleil quotidien.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a29', text: 'Ta présence rend chaque journée spéciale.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a30', text: 'Tu es la personne la plus étonnante que je connaisse.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a31', text: 'Ton rire est la plus belle des musiques à mes oreilles.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a32', text: 'Ta beauté me laisse sans voix.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a33', text: 'Ton intelligence est aussi impressionnante que ta beauté.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a34', text: 'Tu es la définition même de la perfection.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a35', text: 'Ton regard est comme une étoile qui guide mes pensées vers toi.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a36', text: 'Ta présence rend chaque instant magique.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a37', text: 'Tu es la personne la plus fascinante que je connaisse.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a38', text: 'Ton sourire est mon plus beau cadeau.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a39', text: 'Ta beauté intérieure brille encore plus que ta beauté extérieure.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a40', text: 'Ton esprit est aussi attirant que ton apparence.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a41', text: 'Tu es la personne la plus charmante que j\'ai jamais rencontrée.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a42', text: 'Ton sourire est mon rayon de soleil quotidien.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a43', text: 'Ta présence rend chaque journée spéciale.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a44', text: 'Tu es la personne la plus étonnante que je connaisse.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a45', text: 'Ton rire est la plus belle des musiques à mes oreilles.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a46', text: 'Ta beauté me laisse sans voix.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a47', text: 'Ton intelligence est aussi impressionnante que ta beauté.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a48', text: 'Tu es la définition même de la perfection.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a49', text: 'Ton regard est comme une étoile qui guide mes pensées vers toi.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a50', text: 'Ta présence rend chaque instant magique.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a51', text: 'Ton sourire est comme une œuvre d\'art qui illumine ma journée.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a52', text: 'Tu es la personne la plus rayonnante que j\'ai jamais rencontrée.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a53', text: 'Ton rire est la plus douce des mélodies pour mon cœur.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a54', text: 'Ta beauté naturelle est tout simplement envoûtante.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a55', text: 'Ton intelligence égale ta beauté, ce qui est exceptionnel.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a56', text: 'Tu es l\'incarnation de la grâce et de la douceur.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a57', text: 'Ton regard est comme une étoile qui guide mes pensées vers toi.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a58', text: 'Ta présence transforme les moments ordinaires en souvenirs précieux.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a59', text: 'Tu es la personne la plus fascinante que je connaisse.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a60', text: 'Ton sourire est un rayon de soleil dans ma vie.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a61', text: 'Ta beauté intérieure rayonne et inspire ceux qui t\'entourent.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a62', text: 'Ton esprit est aussi attrayant que ton magnifique sourire.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a63', text: 'Tu es la personne la plus charmante que j\'ai jamais rencontrée.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a64', text: 'Ton sourire illumine mes journées les plus sombres.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a65', text: 'Ta présence rend chaque journée spéciale et mémorable.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a66', text: 'Tu es la personne la plus étonnante que je connaisse.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a67', text: 'Ton rire est la plus belle des musiques à mes oreilles.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a68', text: 'Ta beauté me laisse sans voix à chaque fois.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a69', text: 'Ton intelligence est aussi impressionnante que ta beauté.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a70', text: 'Tu es la définition même de la perfection à mes yeux.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a71', text: 'Ton regard est comme une boussole qui guide mon cœur.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a72', text: 'Ta présence rend chaque instant magique et précieux.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a73', text: 'Tu es la personne la plus fascinante que je connaisse.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a74', text: 'Ton sourire est le plus beau des cadeaux que la vie m\'ait offert.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a75', text: 'Ta beauté intérieure brille plus fort que le soleil.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a76', text: 'Ton esprit est aussi attirant que ton apparence.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a77', text: 'Tu es la personne la plus charmante que j\'ai jamais rencontrée.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a78', text: 'Ton sourire est mon rayon de soleil quotidien.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a79', text: 'Ta présence rend chaque journée spéciale et unique.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a80', text: 'Tu es la personne la plus étonnante que je connaisse.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a81', text: 'Ton rire est la plus belle des musiques à mes oreilles.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a82', text: 'Ta beauté me laisse sans voix à chaque fois que je te vois.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a83', text: 'Ton intelligence est aussi impressionnante que ton sourire.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a84', text: 'Tu es la définition même de la grâce et de l\'élégance.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a85', text: 'Ton sourire est comme une douce mélodie qui réchauffe mon cœur.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a86', text: 'Tu es la personne la plus éblouissante que j\'ai jamais rencontrée.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a87', text: 'Ton rire est la plus belle des musiques pour mes oreilles.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a88', text: 'Ta beauté est un véritable chef-d\'œuvre de la nature.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a89', text: 'Ton intelligence égale ta beauté, ce qui est exceptionnel.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a90', text: 'Tu es l\'incarnation de la grâce et de la douceur.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a91', text: 'Ton regard est comme une étoile qui guide mes pensées vers toi.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a92', text: 'Ta présence transforme les moments ordinaires en souvenirs précieux.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a93', text: 'Tu es la personne la plus fascinante que je connaisse.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a94', text: 'Ton sourire est un rayon de soleil dans ma vie.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a95', text: 'Ta beauté intérieure rayonne et inspire ceux qui t\'entourent.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a96', text: 'Ton esprit est aussi attrayant que ton magnifique sourire.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a97', text: 'Tu es la personne la plus charmante que j\'ai jamais rencontrée.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a98', text: 'Ton sourire illumine mes journées les plus sombres.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a99', text: 'Ta présence rend chaque journée spéciale et mémorable.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a100', text: 'Tu es la personne la plus étonnante que je connaisse.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a101', text: 'Ton rire est la plus belle des musiques à mes oreilles.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a102', text: 'Ta beauté me laisse sans voix à chaque fois.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a103', text: 'Ton intelligence est aussi impressionnante que ta beauté.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a104', text: 'Tu es la définition même de la perfection à mes yeux.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a105', text: 'Ton regard est comme une boussole qui guide mon cœur.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a106', text: 'Ta présence rend chaque instant magique et précieux.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a107', text: 'Tu es la personne la plus fascinante que je connaisse.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a108', text: 'Ton sourire est le plus beau des cadeaux que la vie m\'ait offert.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a109', text: 'Ta beauté intérieure brille plus fort que le soleil.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a110', text: 'Ton esprit est aussi attirant que ton apparence.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a111', text: 'Tu es la personne la plus charmante que j\'ai jamais rencontrée.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a112', text: 'Ton sourire est mon rayon de soleil quotidien.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a113', text: 'Ta présence rend chaque journée spéciale et unique.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a114', text: 'Tu es la personne la plus étonnante que je connaisse.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a115', text: 'Ton rire est la plus belle des musiques à mes oreilles.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a116', text: 'Ta beauté me laisse sans voix à chaque fois que je te vois.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a117', text: 'Ton intelligence est aussi impressionnante que ton sourire.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a118', text: 'Tu es la définition même de la grâce et de l\'élégance.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a119', text: 'Ton sourire est comme une douce mélodie qui réchauffe mon cœur.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a120', text: 'Tu es la personne la plus éblouissante que j\'ai jamais rencontrée.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a121', text: 'Ton rire est la plus belle des musiques pour mes oreilles.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a122', text: 'Ta beauté est un véritable chef-d\'œuvre de la nature.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a123', text: 'Ton intelligence égale ta beauté, ce qui est exceptionnel.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a124', text: 'Tu es l\'incarnation de la grâce et de la douceur.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a125', text: 'Ton regard est comme une étoile qui guide mes pensées vers toi.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a126', text: 'Ta présence transforme les moments ordinaires en souvenirs précieux.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a127', text: 'Tu es la personne la plus fascinante que je connaisse.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a128', text: 'Ton sourire est un rayon de soleil dans ma vie.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a129', text: 'Ta beauté intérieure rayonne et inspire ceux qui t\'entourent.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a130', text: 'Ton esprit est aussi attrayant que ton magnifique sourire.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a131', text: 'Tu es la personne la plus charmante que j\'ai jamais rencontrée.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a132', text: 'Ton sourire illumine mes journées les plus sombres.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a133', text: 'Ta présence rend chaque journée spéciale et mémorable.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'a134', text: 'Tu es la personne la plus étonnante que je connaisse.', category: 'flatterie', context: 'doux', intensity: 3),
    PickupLine(id: 'f21', text: 'Si la beauté était un crime, tu serais condamné à vie dans mon cœur.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f22', text: 'Ton regard est comme un aimant, impossible de détourner les yeux.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f23', text: 'Si j\'étais un chat, je ronronnerais rien qu\'à ton contact.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f24', text: 'Ton sourire est comme une drogue, une seule dose et j\'en veux plus.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f25', text: 'Je ne suis pas un photographe, mais je peux certainement nous imaginer ensemble... toute la nuit.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f26', text: 'Ton nom doit être Google, car tu as tout ce que je cherche... et plus encore.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f27', text: 'Si j\'étais un oiseau, je construirais mon nid dans tes bras.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f28', text: 'Ton sourire est comme un rayon X... il me traverse de part en part.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f29', text: 'Je ne suis pas un dictionnaire, mais je peux te faire dire \'Oh mon Dieu\' toute la nuit.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f210', text: 'Ton regard est plus enivrant que le meilleur des vins... et j\'ai très soif.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f2', text: 'Tu es si belle que tu devrais être interdite.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f3', text: 'Ton sourire est comme un coup de foudre, il me laisse sans voix.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f4', text: 'Je ne suis pas un artiste, mais je peux te peindre dans mon cœur.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f5', text: 'Ton regard est comme un feu qui brûle en moi.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f6', text: 'Si j\'étais un poète, je t\'écrirais des vers éternels.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f7', text: 'Ton sourire est comme une musique qui me fait danser.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f8', text: 'Je ne suis pas un magicien, mais je peux te faire disparaître dans mes bras.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f9', text: 'Ton regard est comme un miroir qui reflète mon âme.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f10', text: 'Si j\'étais un roi, je te ferais ma reine.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f11', text: 'Ton sourire est comme un trésor que je veux découvrir.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f12', text: 'Je ne suis pas un explorateur, mais je veux découvrir ton cœur.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f13', text: 'Ton regard est comme une carte qui me guide vers toi.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f14', text: 'Si j\'étais un musicien, je jouerais pour toi seule.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f15', text: 'Ton sourire est comme une fleur qui s\'ouvre dans mon cœur.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f16', text: 'Je ne suis pas un écrivain, mais je veux écrire notre histoire.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f17', text: 'Ton regard est comme un phare qui me guide dans la nuit.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f18', text: 'Si j\'étais un peintre, je te peindrais dans des couleurs vives.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f19', text: 'Ton sourire est comme un soleil qui éclaire ma journée.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f20', text: 'Je ne suis pas un poète, mais je veux te dédier des vers.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f31', text: 'Ton regard est comme une tempête qui fait chavirer mon cœur.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f32', text: 'Si j\'étais un voleur, je déroberais ton cœur en un clin d\'œil.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f33', text: 'Ton sourire est comme un aimant qui attire toutes mes pensées.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f34', text: 'Je ne suis pas un magicien, mais je peux te faire disparaître dans mes bras.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f35', text: 'Ton regard est comme une flèche qui a atteint ma cible.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f36', text: 'Si j\'étais un oiseau, je chanterais pour toi toute la journée.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f37', text: 'Ton sourire est comme un rayon de lune qui éclaire ma nuit.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f38', text: 'Je ne suis pas un artiste, mais je veux peindre ton sourire dans ma mémoire.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f39', text: 'Ton regard est comme une étoile qui guide mes rêves.', category: 'audacieux', context: 'chaud', intensity: 5),
    PickupLine(id: 'f40', text: 'Si j\'étais un écrivain, je t\'écrirais des lettres d\'amour éternelles.', category: 'audacieux', context: 'chaud', intensity: 5)
  ];

  /// Génère une phrase d'accroche aléatoire
  static Future<PickupLine> generateRandomPickupLine() async {
    if (_pickupLinesDatabase.isEmpty) {
      throw Exception('Aucune phrase d\'accroche disponible');
    }
    final random = Random();
    final randomIndex = random.nextInt(_pickupLinesDatabase.length);
    return _pickupLinesDatabase[randomIndex];
  }
}
