// Corrige ou commente l'import si le fichier n'existe pas
// import '../utils/app_theme.dart';

import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: const [
          SplashScreen2(),
        ]),
      ),
    );
  }
}

class SplashScreen2 extends StatelessWidget {
  const SplashScreen2({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 926,
          clipBehavior: Clip.antiAlias,
          decoration: const BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.05, 1.56),
              end: Alignment(0.50, -0.32),
              colors: [Color.fromARGB(255, 18, 32, 47), Color.fromARGB(255, 255, 255, 255)],
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 312,
                child: Container(
                  width: 428,
                  height: 302,
                  decoration: const BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage('assets/images/logo.png'),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 620.93,
                top: 778.31,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-2.09),
                  width: 1347.86,
                  height: 777,
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      begin: const Alignment(0.50, -0.00),
                      end: const Alignment(0.50, 1.00),
                      colors: [Colors.white, Colors.white.withValues(alpha: 0)],
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}