// Corrige ou commente l'import si le fichier n'existe pas
// import '../utils/app_theme.dart';

import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: const [
          SplashScreen4(),
        ]),
      ),
    );
  }
}

class SplashScreen4 extends StatelessWidget {
  const SplashScreen4({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 926,
          clipBehavior: Clip.antiAlias,
          decoration: const BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.05, 1.02),
              end: Alignment(0.96, -0.02),
              colors: [Color(0xFF123456), Color(0xFF654321), Colors.white],
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 312,
                child: Container(
                  width: 428,
                  height: 302,
                  decoration: const BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage('assets/images/logo.png'),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 304,
                top: -24,
                child: Container(
                  width: 248,
                  height: 248,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: const Alignment(0.50, -0.00),
                      end: const Alignment(0.50, 1.00),
                      colors: [Colors.white.withValues(alpha: 0), Colors.white],
                    ),
                    shape: const OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: -184,
                top: 65,
                child: Container(
                  width: 398,
                  height: 398,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: const Alignment(0.50, -0.00),
                      end: const Alignment(0.50, 1.00),
                      colors: [Colors.white.withValues(alpha: 0), Colors.white],
                    ),
                    shape: const OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: -203.12,
                top: 1130.62,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.31),
                  width: 624,
                  height: 624,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: const Alignment(0.50, -0.00),
                      end: const Alignment(0.50, 1.00),
                      colors: [Colors.white.withValues(alpha: 0), Colors.white],
                    ),
                    shape: const OvalBorder(),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}