name: iOS Build and Sign

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Setup iOS certificates
      run: |
        # Create keychain
        security create-keychain -p "" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain
        security set-keychain-settings build.keychain
        
        # Import distribution certificate with proper trust settings
        echo "${{ secrets.DISTRIBUTION_CERTIFICATE }}" | base64 -d > distribution_certificate.p12
        security import distribution_certificate.p12 -k build.keychain -P "${{ secrets.CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign -A
        
        # Import provisioning profile
        echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 -d > Smooth_AI_App_Store-2.mobileprovision
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp Smooth_AI_App_Store-2.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
        
        # Set key partition list for code signing
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain
        
        # List certificates to verify import
        echo "Available certificates:"
        security find-identity -v -p codesigning build.keychain
        
        # Verify provisioning profile
        echo "Provisioning profiles:"
        ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
        
        # Set environment variables for code signing
        echo "CERTIFICATE_NAME=$(security find-identity -v -p codesigning build.keychain | grep 'iPhone Distribution' | head -1 | cut -d'"' -f2)" >> $GITHUB_ENV
        
    - name: Build iOS app
      run: |
        cd ios
        flutter build ios --release --no-codesign
        
    - name: Configure Xcode project for automatic signing
      run: |
        cd ios
        # Set automatic signing for the Runner target
        sed -i '' 's/CODE_SIGN_STYLE = Manual;/CODE_SIGN_STYLE = Automatic;/g' Runner.xcodeproj/project.pbxproj
        sed -i '' 's/PROVISIONING_PROFILE_SPECIFIER = "Smooth AI App Store";/PROVISIONING_PROFILE_SPECIFIER = "";/g' Runner.xcodeproj/project.pbxproj
        sed -i '' 's/DEVELOPMENT_TEAM = "";/DEVELOPMENT_TEAM = 7BHY8D9X9V;/g' Runner.xcodeproj/project.pbxproj
        # Remove manual code signing identity
        sed -i '' 's/CODE_SIGN_IDENTITY = "iPhone Distribution";/CODE_SIGN_IDENTITY = "";/g' Runner.xcodeproj/project.pbxproj
        sed -i '' 's/CODE_SIGN_IDENTITY = "Apple Distribution";/CODE_SIGN_IDENTITY = "";/g' Runner.xcodeproj/project.pbxproj
        
    - name: Archive and sign
      run: |
        cd ios
        xcodebuild -workspace Runner.xcworkspace \
                   -scheme Runner \
                   -configuration Release \
                   -archivePath Runner.xcarchive \
                   -destination generic/platform=iOS \
                   -allowProvisioningUpdates \
                   -allowProvisioningDeviceRegistration \
                   DEVELOPMENT_TEAM="7BHY8D9X9V" \
                   CODE_SIGN_STYLE="Automatic" \
                   archive
                   
    - name: Export IPA
      run: |
        cd ios
        # Verify certificate is imported
        echo "Available certificates:"
        security find-identity -v -p codesigning build.keychain
        
        # Get the certificate identity from the imported certificate
        CERT_IDENTITY=$(security find-identity -v -p codesigning build.keychain | grep "iPhone Distribution" | head -1 | cut -d'"' -f2)
        echo "Using certificate: $CERT_IDENTITY"
        
        if [ -z "$CERT_IDENTITY" ]; then
          echo "Error: No iPhone Distribution certificate found"
          exit 1
        fi
        
        xcodebuild -exportArchive \
                   -archivePath Runner.xcarchive \
                   -exportPath ./build/ios/ipa \
                   -exportOptionsPlist exportOptions.plist \
                   CODE_SIGN_IDENTITY="$CERT_IDENTITY" \
                   DEVELOPMENT_TEAM="7BHY8D9X9V"
                   
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: smooth-ai-ipa
        path: ios/build/ios/ipa/Runner.ipa
        
    - name: Upload to App Store Connect
      if: github.ref == 'refs/heads/main'
      run: |
        xcrun altool --upload-app \
                     --type ios \
                     --file ios/build/ios/ipa/Runner.ipa \
                     --username "${{ secrets.APPLE_ID }}" \
                     --password "${{ secrets.APP_SPECIFIC_PASSWORD }}" \
                     --asc-provider "7BHY8D9X9V" 