name: iOS Build and Sign

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
        
    - name: Install Fastlane
      run: |
        gem install fastlane
        
    - name: Install dependencies
      run: |
        flutter pub get
        cd ios
        pod install
      
    - name: Configure Apple account
      run: |
        # Create keychain for Apple account
        security create-keychain -p "" apple.keychain
        security default-keychain -s apple.keychain
        security unlock-keychain -p "" apple.keychain
        security set-keychain-settings apple.keychain
        
        # Configure Apple account using xcrun
        xcrun altool --store-password-in-keychain-item "AC_PASSWORD" \
          -u "${{ secrets.APPLE_ID }}" \
          -p "${{ secrets.APP_SPECIFIC_PASSWORD }}"
        
        # Verify account configuration
        xcrun altool --list-providers -u "${{ secrets.APPLE_ID }}" -p "${{ secrets.APP_SPECIFIC_PASSWORD }}"
        
        # Set environment variables for Xcode
        echo "DEVELOPMENT_TEAM=7BHY8D9X9V" >> $GITHUB_ENV
        echo "CODE_SIGN_STYLE=Automatic" >> $GITHUB_ENV
        echo "APPLE_ID=${{ secrets.APPLE_ID }}" >> $GITHUB_ENV
        
    - name: Configure Xcode account
      run: |
        # Configure Xcode to use the Apple account
        xcrun simctl list devices
        xcrun xcodebuild -version
        
        # Set up Xcode account using xcrun
        xcrun xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme Runner
        
        # Try to configure account using xcrun with environment variables
        cd ios
        xcrun xcodebuild -workspace Runner.xcworkspace \
               -scheme Runner \
               -configuration Release \
               -destination generic/platform=iOS \
               -allowProvisioningUpdates \
               -allowProvisioningDeviceRegistration \
               DEVELOPMENT_TEAM="7BHY8D9X9V" \
               CODE_SIGN_STYLE="Automatic" \
               -showBuildSettings | grep -E "(DEVELOPMENT_TEAM|CODE_SIGN_STYLE|PRODUCT_BUNDLE_IDENTIFIER)"
        
    - name: Build iOS app
      run: |
        cd ios
        # Use xcodebuild directly instead of flutter build to enable automatic signing
        xcodebuild -workspace Runner.xcworkspace \
                   -scheme Runner \
                   -configuration Release \
                   -destination generic/platform=iOS \
                   -allowProvisioningUpdates \
                   -allowProvisioningDeviceRegistration \
                   DEVELOPMENT_TEAM="7BHY8D9X9V" \
                   CODE_SIGN_STYLE="Automatic" \
                   build
        
    - name: Archive and sign
      run: |
        cd ios
        xcodebuild -workspace Runner.xcworkspace \
                   -scheme Runner \
                   -configuration Release \
                   -archivePath Runner.xcarchive \
                   -destination generic/platform=iOS \
                   -allowProvisioningUpdates \
                   -allowProvisioningDeviceRegistration \
                   DEVELOPMENT_TEAM="7BHY8D9X9V" \
                   CODE_SIGN_STYLE="Automatic" \
                   archive
                   
    - name: Export IPA
      run: |
        cd ios
        xcodebuild -exportArchive \
                   -archivePath Runner.xcarchive \
                   -exportPath ./build/ios/ipa \
                   -exportOptionsPlist exportOptions.plist \
                   -allowProvisioningUpdates \
                   -allowProvisioningDeviceRegistration \
                   DEVELOPMENT_TEAM="7BHY8D9X9V"
                   
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: smooth-ai-ipa
        path: ios/build/ios/ipa/Runner.ipa
        
    - name: Upload to App Store Connect
      if: github.ref == 'refs/heads/main'
      run: |
        xcrun altool --upload-app \
                     --type ios \
                     --file ios/build/ios/ipa/Runner.ipa \
                     --username "${{ secrets.APPLE_ID }}" \
                     --password "${{ secrets.APP_SPECIFIC_PASSWORD }}" \
                     --asc-provider "7BHY8D9X9V" 