name: iOS Build and Sign

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Configure Apple account
      run: |
        # Create keychain for Apple account
        security create-keychain -p "" apple.keychain
        security default-keychain -s apple.keychain
        security unlock-keychain -p "" apple.keychain
        security set-keychain-settings apple.keychain
        
        # Configure Apple account for automatic signing
        xcrun notarytool store-credentials "apple-account" \
          --apple-id "${{ secrets.APPLE_ID }}" \
          --password "${{ secrets.APP_SPECIFIC_PASSWORD }}" \
          --team-id "7BHY8D9X9V"
        
    - name: Build iOS app
      run: |
        cd ios
        flutter build ios --release
        
    - name: Archive and sign
      run: |
        cd ios
        xcodebuild -workspace Runner.xcworkspace \
                   -scheme Runner \
                   -configuration Release \
                   -archivePath Runner.xcarchive \
                   -destination generic/platform=iOS \
                   -allowProvisioningUpdates \
                   -allowProvisioningDeviceRegistration \
                   DEVELOPMENT_TEAM="7BHY8D9X9V" \
                   CODE_SIGN_STYLE="Automatic" \
                   archive
                   
    - name: Export IPA
      run: |
        cd ios
        xcodebuild -exportArchive \
                   -archivePath Runner.xcarchive \
                   -exportPath ./build/ios/ipa \
                   -exportOptionsPlist exportOptions.plist \
                   -allowProvisioningUpdates \
                   -allowProvisioningDeviceRegistration \
                   DEVELOPMENT_TEAM="7BHY8D9X9V"
                   
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: smooth-ai-ipa
        path: ios/build/ios/ipa/Runner.ipa
        
    - name: Upload to App Store Connect
      if: github.ref == 'refs/heads/main'
      run: |
        xcrun altool --upload-app \
                     --type ios \
                     --file ios/build/ios/ipa/Runner.ipa \
                     --username "${{ secrets.APPLE_ID }}" \
                     --password "${{ secrets.APP_SPECIFIC_PASSWORD }}" \
                     --asc-provider "7BHY8D9X9V" 