name: iOS Build and Sign

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Setup iOS certificates
      run: |
        # Create keychain
        security create-keychain -p "" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain
        security set-keychain-settings build.keychain
        
        # Import distribution certificate
        echo "${{ secrets.DISTRIBUTION_CERTIFICATE }}" | base64 -d > distribution_certificate.p12
        security import distribution_certificate.p12 -k build.keychain -P "${{ secrets.CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
        
        # Import provisioning profile
        echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 -d > Smooth_AI_App_Store-2.mobileprovision
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp Smooth_AI_App_Store-2.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
        
        # Set code signing identity
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain
        
        # List certificates to verify import
        security find-identity -v -p codesigning build.keychain
        
    - name: Build iOS app
      run: |
        cd ios
        flutter build ios --release --no-codesign
        
    - name: Archive and sign
      run: |
        cd ios
        xcodebuild -workspace Runner.xcworkspace \
                   -scheme Runner \
                   -configuration Release \
                   -archivePath Runner.xcarchive \
                   -destination generic/platform=iOS \
                   -allowProvisioningUpdates \
                   -allowProvisioningDeviceRegistration \
                   CODE_SIGN_IDENTITY="iPhone Distribution" \
                   PROVISIONING_PROFILE_SPECIFIER="Smooth_AI_App_Store-2" \
                   DEVELOPMENT_TEAM="7BHY8D9X9V" \
                   archive
                   
    - name: Export IPA
      run: |
        cd ios
        xcodebuild -exportArchive \
                   -archivePath Runner.xcarchive \
                   -exportPath ./build/ios/ipa \
                   -exportOptionsPlist exportOptions.plist
                   
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: smooth-ai-ipa
        path: ios/build/ios/ipa/Runner.ipa
        
    - name: Upload to App Store Connect
      if: github.ref == 'refs/heads/main'
      run: |
        xcrun altool --upload-app \
                     --type ios \
                     --file ios/build/ios/ipa/Runner.ipa \
                     --username "${{ secrets.APPLE_ID }}" \
                     --password "${{ secrets.APP_SPECIFIC_PASSWORD }}" \
                     --asc-provider "7BHY8D9X9V" 